"""table utilisateur ajouter utilisateur

Revision ID: 5dcd5e5b9b59
Revises: c096e987225e
Create Date: 2020-09-10 09:31:19.407368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dcd5e5b9b59'
down_revision = 'c096e987225e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateur', sa.Column('a_propos_de_moi', sa.String(length=140), nullable=True))
    op.add_column('utilisateur', sa.Column('avatar', sa.Text(length=131072), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utilisateur', 'avatar')
    op.drop_column('utilisateur', 'a_propos_de_moi')
    # ### end Alembic commands ###
