"""empty message

Revision ID: 8f38e9c2d97b
Revises: 5dcd5e5b9b59
Create Date: 2020-09-17 08:56:02.039904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f38e9c2d97b'
down_revision = '5dcd5e5b9b59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateur', sa.Column('dernier_acces', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utilisateur', 'dernier_acces')
    # ### end Alembic commands ###
