"""jeton

Revision ID: af783f6d6a0f
Revises: 15f195f135c8
Create Date: 2020-10-26 16:57:21.692143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af783f6d6a0f'
down_revision = '15f195f135c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateur', sa.Column('jeton', sa.String(length=32), nullable=True))
    op.add_column('utilisateur', sa.Column('jeton_expiration', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_utilisateur_jeton'), 'utilisateur', ['jeton'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_utilisateur_jeton'), table_name='utilisateur')
    op.drop_column('utilisateur', 'jeton_expiration')
    op.drop_column('utilisateur', 'jeton')
    # ### end Alembic commands ###
